services:
  spring-backend:
    build: .
    container_name: spring-backend-places
    command: java -jar places.jar
    volumes:
      - .:/app
    ports:
      - "8090:8090"
    env_file:
      - .env
    networks:
      - dbp

networks:
  dbp:
    external: true
