services:
  spring-backend:
    build: .
    container_name: spring-backend-usuarios
    command: java -jar usuarios.jar
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    networks:
      - dbp

networks:
  dbp:
    external: true
