version: '3'

services:
  node-backend:
    build:
      dockerfile: Dockerfile
    container_name: microservicio-mensajeria
    command: node server.js
    volumes:
      - .:/app
    ports:
      - "2500:2500"
    env_file:
      - .env
    networks:
      - dbp

networks:
  dbp:
    external: true
