version: '3'

services:
  node-backend:
    build: .
    container_name: node-backend-notificaciones
    command: node server.js
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:                
      - .env
    networks:
      - dbp

networks:
  dbp:
    external: true
